cmake_minimum_required(VERSION 3.20.0)
find_package(Zephyr REQUIRED HINTS $ENV{ZEPHYR_BASE})

project(src)

target_sources(app PRIVATE
    src/main.c
    libtommath/mp_2expt.c
    libtommath/mp_abs.c
    libtommath/mp_add.c
    libtommath/mp_add_d.c
    libtommath/mp_addmod.c
    libtommath/mp_and.c
    libtommath/mp_clamp.c
    libtommath/mp_clear.c
    libtommath/mp_clear_multi.c
    libtommath/mp_cmp.c
    libtommath/mp_cmp_d.c
    libtommath/mp_cmp_mag.c
    libtommath/mp_cnt_lsb.c
    libtommath/mp_complement.c
    libtommath/mp_copy.c
    libtommath/mp_count_bits.c
    libtommath/mp_cutoffs.c
    libtommath/mp_div.c
    libtommath/mp_div_2.c
    libtommath/mp_div_2d.c
    libtommath/mp_div_d.c
    libtommath/mp_dr_is_modulus.c
    libtommath/mp_dr_reduce.c
    libtommath/mp_dr_setup.c
    libtommath/mp_error_to_string.c
    libtommath/mp_exch.c
    libtommath/mp_expt_n.c
    libtommath/mp_exptmod.c
    libtommath/mp_exteuclid.c
    libtommath/mp_fread.c
    libtommath/mp_from_sbin.c
    libtommath/mp_from_ubin.c
    libtommath/mp_fwrite.c
    libtommath/mp_gcd.c
    libtommath/mp_get_double.c
    libtommath/mp_get_i32.c
    libtommath/mp_get_i64.c
    libtommath/mp_get_l.c
    libtommath/mp_get_mag_u32.c
    libtommath/mp_get_mag_u64.c
    libtommath/mp_get_mag_ul.c
    libtommath/mp_grow.c
    libtommath/mp_hash.c
    libtommath/mp_init.c
    libtommath/mp_init_copy.c
    libtommath/mp_init_i32.c
    libtommath/mp_init_i64.c
    libtommath/mp_init_l.c
    libtommath/mp_init_multi.c
    libtommath/mp_init_set.c
    libtommath/mp_init_size.c
    libtommath/mp_init_u32.c
    libtommath/mp_init_u64.c
    libtommath/mp_init_ul.c
    libtommath/mp_invmod.c
    libtommath/mp_is_square.c
    libtommath/mp_kronecker.c
    libtommath/mp_lcm.c
    libtommath/mp_log.c
    libtommath/mp_log_n.c
    libtommath/mp_lshd.c
    libtommath/mp_mod.c
    libtommath/mp_mod_2d.c
    libtommath/mp_montgomery_calc_normalization.c
    libtommath/mp_montgomery_reduce.c
    libtommath/mp_montgomery_setup.c
    libtommath/mp_mul.c
    libtommath/mp_mul_2.c
    libtommath/mp_mul_2d.c
    libtommath/mp_mul_d.c
    libtommath/mp_mulmod.c
    libtommath/mp_neg.c
    libtommath/mp_or.c
    libtommath/mp_pack.c
    libtommath/mp_pack_count.c
    libtommath/mp_prime_fermat.c
    libtommath/mp_prime_frobenius_underwood.c
    libtommath/mp_prime_is_prime.c
    libtommath/mp_prime_miller_rabin.c
    libtommath/mp_prime_next_prime.c
    libtommath/mp_prime_rabin_miller_trials.c
    libtommath/mp_prime_rand.c
    libtommath/mp_prime_strong_lucas_selfridge.c
    libtommath/mp_radix_size.c
    libtommath/mp_radix_size_overestimate.c
    libtommath/mp_rand.c
    libtommath/mp_rand_source.c
    libtommath/mp_read_radix.c
    libtommath/mp_reduce.c
    libtommath/mp_reduce_2k.c
    libtommath/mp_reduce_2k_l.c
    libtommath/mp_reduce_2k_setup.c
    libtommath/mp_reduce_2k_setup_l.c
    libtommath/mp_reduce_is_2k.c
    libtommath/mp_reduce_is_2k_l.c
    libtommath/mp_reduce_setup.c
    libtommath/mp_root_n.c
    libtommath/mp_rshd.c
    libtommath/mp_sbin_size.c
    libtommath/mp_set.c
    libtommath/mp_set_double.c
    libtommath/mp_set_i32.c
    libtommath/mp_set_i64.c
    libtommath/mp_set_l.c
    libtommath/mp_set_u32.c
    libtommath/mp_set_u64.c
    libtommath/mp_set_ul.c
    libtommath/mp_shrink.c
    libtommath/mp_signed_rsh.c
    libtommath/mp_sqrmod.c
    libtommath/mp_sqrt.c
    libtommath/mp_sqrtmod_prime.c
    libtommath/mp_sub.c
    libtommath/mp_sub_d.c
    libtommath/mp_submod.c
    libtommath/mp_to_radix.c
    libtommath/mp_to_sbin.c
    libtommath/mp_to_ubin.c
    libtommath/mp_ubin_size.c
    libtommath/mp_unpack.c
    libtommath/mp_warray_free.c
    libtommath/mp_xor.c
    libtommath/mp_zero.c
    libtommath/s_mp_add.c
    libtommath/s_mp_copy_digs.c
    libtommath/s_mp_div_3.c
    libtommath/s_mp_div_recursive.c
    libtommath/s_mp_div_school.c
    libtommath/s_mp_div_small.c
    libtommath/s_mp_exptmod.c
    libtommath/s_mp_exptmod_fast.c
    libtommath/s_mp_fp_log.c
    libtommath/s_mp_fp_log_d.c
    libtommath/s_mp_get_bit.c
    libtommath/s_mp_invmod.c
    libtommath/s_mp_invmod_odd.c
    libtommath/s_mp_log_2expt.c
    libtommath/s_mp_montgomery_reduce_comba.c
    libtommath/s_mp_mul.c
    libtommath/s_mp_mul_balance.c
    libtommath/s_mp_mul_comba.c
    libtommath/s_mp_mul_high.c
    libtommath/s_mp_mul_high_comba.c
    libtommath/s_mp_mul_karatsuba.c
    libtommath/s_mp_mul_toom.c
    libtommath/s_mp_prime_is_divisible.c
    libtommath/s_mp_prime_tab.c
    libtommath/s_mp_radix_map.c
    libtommath/s_mp_radix_size_overestimate.c
    libtommath/s_mp_rand_platform.c
    libtommath/s_mp_rand_source.c
    libtommath/s_mp_sqr.c
    libtommath/s_mp_sqr_comba.c
    libtommath/s_mp_sqr_karatsuba.c
    libtommath/s_mp_sqr_toom.c
    libtommath/s_mp_sub.c
    libtommath/s_mp_warray.c
    libtommath/s_mp_warray_get.c
    libtommath/s_mp_warray_put.c
    libtommath/s_mp_zero_buf.c
    libtommath/s_mp_zero_digs.c
)


target_include_directories(app PRIVATE
    libtommath
)