<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <AssemblyName>client</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>True</UseWindowsForms>
    <TargetFramework>net35</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>Preview</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup />
  <ItemGroup>
    <Reference Include="System.Core">
      <HintPath>/usr/share/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.Core.dll</HintPath>
    </Reference>
    <Reference Include="System.Management" />
    <Reference Include="Interop.TaskScheduler" />
    <Reference Include="System.ServiceModel.Web">
      <HintPath>/usr/share/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.ServiceModel.Web.dll</HintPath>
    </Reference>
    <Reference Include="System.Runtime.Serialization">
      <HintPath>/usr/share/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.Runtime.Serialization.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>