default "!";
"A" "Y";
"B" "C";
"C" "R";
"D" "K";
"E" "Z";
"F" "B";
"G" "0";
"H" "H";
"I" "G";
"J" "8";
"K" "V";
"L" "6";
"M" "+";
"N" "%";
"O" "1";
"P" "A";
"Q" "9";
"R" "P";
"S" "I";
"T" "7";
"U" "D";
"V" "Q";
"W" "O";
"X" "J";
"Y" "U";
"Z" "5";
"0" "@";
"1" "W";
"2" "X";
"3" "S";
"4" "L";
"5" "M";
"6" "T";
"7" "3";
"8" "4";
"9" "E";
"%" "N";
"@" "2";
"+" "F";
