default "!";
"A" "Q";
"B" "Y";
"C" "O";
"D" "X";
"E" "8";
"F" "W";
"G" "1";
"H" "L";
"I" "Z";
"J" "V";
"K" "J";
"L" "A";
"M" "G";
"N" "S";
"O" "N";
"P" "3";
"Q" "E";
"R" "5";
"S" "2";
"T" "4";
"U" "+";
"V" "6";
"W" "B";
"X" "9";
"Y" "C";
"Z" "0";
"0" "U";
"1" "D";
"2" "M";
"3" "H";
"4" "K";
"5" "R";
"6" "@";
"7" "7";
"8" "%";
"9" "T";
"%" "F";
"@" "I";
"+" "P";
