default "!";
"a" "Q";
"b" "W";
"c" "7";
"d" "V";
"e" "1";
"f" "X";
"g" "9";
"h" "S";
"i" "5";
"j" "Y";
"k" "Z";
"l" "F";
"m" "K";
"n" "8";
"o" "O";
"p" "J";
"q" "H";
"r" "M";
"s" "2";
"t" "6";
"u" "G";
"v" "0";
"w" "R";
"x" "C";
"y" "3";
"z" "+";
"0" "A";
"1" "U";
"2" "4";
"3" "E";
"4" "B";
"5" "I";
"6" "P";
"7" "%";
"8" "L";
"9" "@";
"_" "T";
"{" "N";
"}" "D";
