apiVersion: berg.norelect.ch/v1
kind: Challenge
metadata:
  name: origami
  namespace: berg
spec:
  categories:
    - crypto
  difficulty: easy
  author: Zukane
  displayName: Origami
  allowOutboundTraffic: false
  flag: NNS{k33p_f0ld1ng_4nd_f0ld1ng_l1k3_4n_0r1g4m1_m4st3r}
  flagFormat: NNS{...}
  description: |
    Origami is a ntruly marvellous artform
  containers: []
  attachments:
    - fileName: origami.tar.gz
      downloadUrl: "${handouts}/origami.tar.gz"
