[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/run/supervisord.pid

[program:k3s]
command=k3s server --cluster-cidr=10.244.0.0/16 --service-cidr=10.245.0.0/16 --snapshotter=overlayfs --kubelet-arg=local-storage-capacity-isolation=false --kubelet-arg=eviction-hard= --disable=traefik --disable=servicelb --disable=local-storage --disable=metrics-server --disable=coredns --disable-helm-controller --disable-network-policy
priority=10
autorestart=true
startsecs=5
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:bootstrap]
command=/usr/local/bin/bootstrap
priority=20
autorestart=unexpected
startretries=20
restartpause=5
startsecs=0
exitcodes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:registry]
command=/bin/sh -c 'until kubectl get ns triangle-origins >/dev/null 2>&1; do sleep 2; done; exec /usr/local/bin/registry'
priority=30
autorestart=true
startsecs=5
startretries=100
restartpause=5
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:operator]
command=/bin/sh -c 'until kubectl get crd sites.triangle.io >/dev/null 2>&1; do sleep 2; done; exec /usr/local/bin/operator'
priority=30
autorestart=true
startsecs=5
startretries=100
restartpause=5
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:frontend]
command=/bin/sh -c 'until [ -s /out/token ]; do sleep 2; done; exec /bin/env -i /bin/start-stop-daemon --start --chuid 1000:1000 --exec /usr/local/bin/frontend'
priority=40
autorestart=true
startsecs=5
startretries=100
restartpause=5
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
