[CryptoEngine]
Algorithm = AES-128-GCM
Ciphertext_Target = /tmp/.cache_sys_bak.dat
Chunk_Stride = 16
Block_Nonce_Hex = 9a4bf201cc88102491a0c821
Auth_Tag_Expected = a39f68bc1458e0a1789c24de817f09ac

[DecoyKeySchedule]
Round_0 = RkxBR3tjMG5mMXJtM2RfYg==
Round_1 = eV9jaDRsbF9tNGszcl90aA==
Round_2 = MXNfMXNfdGgzX2ZsNGd9
Master_Expanded_b64 = RkxBR3tjMG5mMXJtM2RfYnlfY2g0bGxfbTRrM3JfdGgxc18xc190aDNfZmw0Z30=
