global
  log stdout format raw local0
  maxconn 4096
  user haproxy
  group haproxy

defaults
  mode http
  log global
  timeout connect 5000
  timeout client 10000
  timeout server 10000

frontend front1
  bind *:${FRONT_PORT}

  acl is_office_web hdr(host) -i mmoffice.x.corp
  acl network_office src 192.168.17.0/24 10.0.17.0/24
  acl is_office_path path,url_dec -i -m sub office
  acl is_multipart req.hdr(Content-Type) -i -m beg multipart/form-data

  http-request deny if is_office_path !network_office
  http-request deny if is_multipart !network_office

  use_backend back1 if is_office_web

backend back1
  server s1 ${BACK_SERVER}:${BACK_PORT}

