default "zz";
"a" "7f";
"b" "59";
"c" "2e";
"d" "42";
"e" "ee";
"f" "40";
"g" "03";
"h" "62";
"i" "13";
"j" "3a";
"k" "d0";
"l" "7d";
"m" "88";
"n" "ea";
"o" "b3";
"p" "49";
"q" "22";
"r" "0a";
"s" "26";
"t" "f2";
"u" "6d";
"v" "3e";
"w" "9f";
"x" "d7";
"y" "dd";
"z" "7c";
"0" "14";
"1" "36";
"2" "e6";
"3" "46";
"4" "06";
"5" "e4";
"6" "ca";
"7" "6b";
"8" "ba";
"9" "66";
"_" "f5";
"{" "34";
"}" "3d";
