server {
    listen       8080;
    server_name  localhost;
    root   /usr/share/nginx/html;
    index  index.html;

    location / {
        try_files $uri $uri/ $uri.html @api;
    }

    location @api {
        proxy_pass https://api:6443;
        proxy_ssl_verify off;
        break;
    }
}