[profile.default]

fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
    { access = "write", path = "./contracts.json" },
]

remappings = [
  "forge-std=lib/forge-std/src/",
]