apiVersion: berg.norelect.ch/v1
kind: Challenge
metadata:
  name: read-the-rules
  namespace: berg
spec:
  displayName: "Read the rules?"
  categories:
    - sanity
  difficulty: easy
  author: 0xle
  allowOutboundTraffic: false
  flag: NNS{W3lc0m3_t0_th3_ctf!_w3_h0p3_y0u_h4v3_fun!}
  flagFormat: NNS{...}
  description: |
    Have you read the rules? Join our Discord server if you haven't done so already: https://discord.gg/9AZr3WKrjG
  containers: []
  attachments: []
